// Class automatically generated by Dev-C++ New Class wizard

#ifndef ABB_H
#define ABB_H

/*
 * No description
 */
class ABB
{
	ABB(){};
	virtual ~ABB(){};
	virtual void insert(int n) = 0;
	virtual void remove(int n) = 0;
	virtual bool find(int n) = 0;
	virtual int min() = 0;
	virtual int max() = 0;
};

#endif // ABB_H
