// Class automatically generated by Dev-C++ New Class wizard

#include "abb.h" // class's header file

// class constructor
ABB::ABB()
{
	// insert your code here
}

// class destructor
ABB::~ABB()
{
	// insert your code here
}
