// Class automatically generated by Dev-C++ New Class wizard

#include "avlabb.h" // class's header file

// class constructor
AVLABB::AVLABB()
{
	// insert your code here
}

// class destructor
AVLABB::~AVLABB()
{
	// insert your code here
}



                    
