// Class automatically generated by Dev-C++ New Class wizard

#ifndef AVLABB_H
#define AVLABB_H

#include "abb.h" // inheriting class's header file

/*
 * No description
 */
class AVLABB : public ABB
{
	public:
		// class constructor
		AVLABB();
		// class destructor
		~AVLABB();
};

#endif // AVLABB_H
