// Class automatically generated by Dev-C++ New Class wizard

#ifndef REDBLACKTREE_H
#define REDBLACKTREE_H

#include "abb.h" // inheriting class's header file

/*
 * No description
 */
class RedBlackTree : public ABB
{
	public:
		// class constructor
		RedBlackTree();
		// class destructor
		~RedBlackTree();
};

#endif // REDBLACKTREE_H
