// Class automatically generated by Dev-C++ New Class wizard

#include "tnode.h" // class's header file

// class constructor
tNode::tNode()
{
	// insert your code here
}

// class destructor
tNode::~tNode()
{
	// insert your code here
}
