// Class automatically generated by Dev-C++ New Class wizard

#ifndef TNODE_H
#define TNODE_H

/*
 * No description
 */
class tNode
{
	public:
		// class constructor
		tNode();
		// class destructor
		~tNode();
};

#endif // TNODE_H
