// Class automatically generated by Dev-C++ New Class wizard

#ifndef TREAP_H
#define TREAP_H
#include <string>
#include "tNode.h"
#include "includes.h"
#include "abb.h" // inheriting class's header file
using namespace std;
// No description
class Treap : public ABB
{
    private:
        tNode* _root;
        tNode* rotLeft(tNode* subRoot);
        tNode* rotRight(tNode* subRoot);
        tNode* findNode(string k);
        void inorderPrint(tNode* currentNode);
        tNode* insertNode(tNode* root,string k, int v, int p);
        
	public:
		// class constructor
		Treap();
		// class destructor
		~Treap();
        void insert(string k,int v);
        void remove(string k);
        int find(string k);
        int min();
        int max();
        void prettyPrint();
        void sortedDump();
};

#endif // TREAP_H
